version: 2.1

orbs:
  python: circleci/python@1.1.0
  codecov: codecov/codecov@1.1.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: poetry run flake8
          name: Lint
      - run:
          command: poetry run coverage run -m runner
          name: Test
      - run:
          command: |
            mkdir -p /tmp/coverage/custom
            poetry run coverage xml -o /tmp/coverage/results.xml
          name: Prepare coverage results
      - store_artifacts:
          path: /tmp/coverage/results.xml
      - codecov/upload:
          file: /tmp/coverage/results.xml

workflows:
  main:
    jobs:
      - build-and-test
